# WARNING: This file is managed automatically and may be overwritten at any time.

name: CI

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]

permissions: {}

jobs:
  Commit:
    uses: schubergphilis-ep/github-terraform-workflows/.github/workflows/commit.yaml@a962b16003d32a7f80fa2f50280acd750e8fdcc3 # v2.3.1
    permissions:
      contents: read
      pull-requests: write
    secrets: inherit

  Terraform:
    uses: schubergphilis-ep/github-terraform-workflows/.github/workflows/module-ci.yaml@a962b16003d32a7f80fa2f50280acd750e8fdcc3 # v2.3.1
    permissions:
      contents: write
      security-events: write
    secrets: inherit
