# WARNING: This file is managed automatically and may be overwritten at any time.

name: CI

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]

jobs:
  Commit:
    uses: schubergphilis-ep/github-terraform-workflows/.github/workflows/commit.yaml@e7b9fcd9a9b85b5c42e690ac140b9def7bee2212 # v2.1.2
    permissions:
      contents: read
      pull-requests: write
    secrets: inherit

  Terraform:
    uses: schubergphilis-ep/github-terraform-workflows/.github/workflows/module-ci.yaml@e7b9fcd9a9b85b5c42e690ac140b9def7bee2212 # v2.1.2
    permissions:
      contents: write
      security-events: write
    secrets: inherit
